[package]
name = "embedded-nand"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["embedded-nand-async", "winbond/w25n"]

[dependencies]
defmt = "0.3.10"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
