[package]
name = "spi-flash"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3.10"
embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
embedded-nand = { path = "../embedded-nand" }
